weights: yolov5l.pt
cfg: ./models/yolov5l.yaml
data: ./data/debris.yaml
hyp: data/hyp.scratch.yaml
epochs: 3
batch_size: 16
img_size:
- 512
- 512
rect: false
resume: false
nosave: true
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 16
world_size: 1
global_rank: -1
